USE Casestudy;

DELETE FROM dbo.Brands;
DELETE FROM dbo.Products;


INSERT INTO dbo.Brands ( Name )
VALUES ( 'Sennheiser' ),
	   ( 'Beyerdynamic' ),
	   ( 'Audio-Technica' );

INSERT INTO dbo.Products (Id, BrandId, ProductName, GraphicName, CostPrice, MSRP, QtyOnHand, QtyOnBackOrder, Description)
VALUES ('0', 1, 'HD 200 Pro Professional Monitoring Headphone', 'hd200.jpg', 59.95, 89.95, 100, 100, 'The HD 200 PRO offers powerful and detailed sound for every monitoring task and for every budget. It combines with an efficient ambient noise reduction with a high resolution. Focus on your mix – at home, in your studio or during live events.'),
		('1', 1, 'HD 598 Cs Closed Back Headphone', 'hd598.jpg', 199.95, 249.99, 100, 100, 'The HD 598 Cs provides impeccable sound quality and effective noise isolation. A closed-back design employing rigorous acoustic engineering, it delivers incredibly natural, detailed and balanced sound allowing enjoyment of your favorite music without disturbing your surroundings or being disturbed by it.'),
		('2', 1, 'HD 599 Open Back Headphone', 'hd599.jpg', 259.99, 299.99, 100, 100, 'The best in class, remastered. The new HD 500 Series pushes performance to the next level. Topping the product line is the HD 599, a premium headphone for those seeking sophisticated sound, design and build quality. Powered by Sennheiser proprietary transducer technology and featuring the Ergonomic Acoustic Refinement (E.A.R) design, the HD 599 represents a step into the world of audiophile sound reproduction. This open back, around ear headphone delivers an impressively natural tonal balance with outstanding spatial performance. Exceptional wearing comfort is provided by large ear cups fitted with plush velour ear cushions. Premium design cues; timeless ivory color scheme, brown headband stitching and matte metallic detail, communicate quality at first glance. Crafted to impress, the HD 599 is a solid choice for music listeners with sense of discovery!'),
		('3', 1, 'HD 280 PRO Headphone', 'hd280.jpg', 119.95, 149.99, 100, 100, 'The HD 280 Pro is Sennheiser''s most significant closed, around-the-ear headphone to be introduced in years. Designed to exceed the demands of the professional environment, the HD 280 Pro boasts extremely robust construction combined with the sound quality, modular design and aggressive noise isolation the necessary in the field. The unique collapsible design, combined with swiveling ear cups, offers maximum flexibility in any application.'),
		('4', 1, 'HD 650 Headphones', 'hd650.jpg', 517.56, 599.99, 100, 100, 'The audiophile HD 650 is the ultimate in open, dynamic headphone design. The HD 650 feature improved materials for even better sound reproduction. They captivate the listener with their expressiveness and emotion while maintaining absolute precision and lifelike reproduction. Enjoy sound in perfection!'),

		('5', 2, 'DT 770 PRO 80 Ohm Studio Headphone', 'dt770.jpg', 239.91, 249.99, 100, 100, 'For years now, professional users all over the world have placed their trust in our classic range: DT 770/880/990 PRO. The studio reference headphone boasts extremely detailed resolution and very transparent sound.'),
		('6', 2, 'DT 880 Premium Chrome', 'dt880.jpg', 272.59, 349.95, 100, 100, 'Proving that not all headphones are created equal, the award-winning Beyerdynamic DT 880 high-end headphones combine the strengths of both open and closed technologies to reproduce the complete sound spectrum in stunning detail. The high frequencies sound crystal clear without ever coming across as unpleasant, the balanced mids sound analytical and strong, and the bass is voluminous without being too obtrusive. In total, the phones produce a rich frequency response of 5 Hz to 35 kHz, making everything from classical music to hip-hop to big-budget movie soundtracks sound rich and immersive. The DT 880 headphones are also extremely comfortable during extended listening sessions, with a single-sided cable, replaceable soft ear pads, and a padded headband. And as an aesthetic bonus, the phones offer classic grilles made of high-grade steel. Other features include a semi-open back design, an innovative bass-reflex system, a gold-plated 1/8-inch mini stereo jack plug, a 1/4-inch adapter, and a black carrying case. Made in Germany, the phones weigh 10.4 ounces and carry a two-year warranty.'),
		('7', 2, 'DT 990 PRO open Studio Headphone', 'dt990.jpg', 219.16, 299.95, 100, 100, 'The DT 990 PRO is the open studio headphone offering spacious sound for long mixing and listening sessions in comfort and without fatigue.'),
		('8', 2, 'DT 1990 PRO Studio open Reference Headphones', 'dt1990.jpg', 738.28, 849.99, 100, 100, 'The DT 1990 Pro reference headphones combine these decades of expertise in headphone technology with the latest Tesla driver technology in an open-back design. thanks to its high-resolution and well-balanced sound The DT 1990 Pro sets new standards, Not least in terms of design and workmanship. as with all Beyer dynamic professional studio Headphones, The DT 1990 Pro is also handcrafted in Germany. Backed by high-quality materials and meticulous workmanship, This high-end product is a long-term investment. together with an ingenious open-back design, The high-resolution Tesla drivers ensure a wide, dynamic and extremely natural stereo image. Titanium-coated acoustic fabric and carefully selected precision-woven textiles round off the balanced sound quality. natural and exceptionally Spatial Sound is achieved thanks to the open-back design. The optimized Spatial Sound reproduction makes the DT 1990 Pro headphones a reliable reference for mixing and mastering applications as well as for critical listening. choose between a well-balanced sound or Analytical sound thanks to replaceable velour ear pads. Both ear pad variants are included to finish off this impeccable studio headphone package'),
		('9', 2, 'Custom One Pro Plus Headphone', 'customonepro.jpg', 223.77, 299.95, 100, 100, 'The Custom series is unique concept in headphone design. It gives you the ability to modify the headphones to your personal style and adapt it according to different situations and modes of use. With these features, the Custom Series creates a new generation of headphones for a new generation of users.'),

		('10', 3, 'ATH-M20x Professional Headphones', 'm20x.jpg', 69.00, 99.95, 100, 100, 'Online reviewers, top audio professionals and cult followers have long agreed that the ATH-M20x is an unmatched combination of audio and build quality, whether in the studio or on the go. That award-winning formula is embodied in the newly remastered M-Series line, with a model perfectly suited for every discerning listener. Contoured earcups seal tight for excellent sound isolation, with minimal bleed. And the pro-grade materials are durable, yet comfortable. M-Series professional monitor headphones deliver accurate audio and outstanding comfort that gets the job done. Hour after hour, year after year.'),
		('11', 3, 'ATH-M30x Professional Headphones', 'm30x.jpg', 88.70, 119.95, 100, 100, 'The M-Series ATH-M30x professional monitor headphones combine modern engineering and high-quality materials to deliver a comfortable listening experience, with enhanced audio clarity and sound isolation. Tuned for highly detailed audio, with strong mid-range definition, these versatile monitoring headphones are ideal in a variety of situations. Designed primarily for studio tracking and mixing, they offer added features for increased portability, making them a great choice for field recording.'),
		('12', 3, 'ATH-M40x Professional Headphones', 'm40x.jpg', 148.56, 179.99, 100, 100, 'Online reviewers, top audio professionals and cult followers have long agreed that the ATH-M40x is an unmatched combination of audio and build quality, whether in the studio or on the go. That award-winning formula is embodied in the newly remastered M-Series line, with a model perfectly suited for every discerning listener. Contoured earcups seal tight for excellent sound isolation, with minimal bleed. And the pro-grade materials are durable, yet comfortable. M-Series professional monitor headphones deliver accurate audio and outstanding comfort that gets the job done. Hour after hour, year after year.'),
		('13', 3, 'ATH-M50x Professional Headphones', 'm50x.jpg', 190.03, 249.95, 100, 100, 'Online reviewers, top audio professionals and cult followers have long agreed that the ATH-M50x is an unmatched combination of audio and build quality, whether in the studio or on the go. That award-winning formula is embodied in the newly remastered M-Series line, with a model perfectly suited for every discerning listener. Contoured earcups seal tight for excellent sound isolation, with minimal bleed. And the pro-grade materials are durable, yet comfortable. M-Series professional monitor headphones deliver accurate audio and outstanding comfort that gets the job done. Hour after hour, year after year.'),
		('14', 3, 'ATH-ADG1X Open Air High-Fidelity', 'adg1x.jpg', 374.94, 399.99, 100, 100, 'With specially designed 53mm drivers, improved 3D Wing Support system and super soft earpads, the ATH-ADG1X open-air gaming headset gives you advanced, high-fidelity sound and a comfortable, secure fit. Plus, the all-metal honeycomb housings keep the headset light and cool, providing an open, natural sound. So you won''t work up a sweat even as you''re cast into the powerfully detailed sonic worlds of today''s FPS (first-person shooter) and other games. To keep you even more in control, the ATH-ADG1X comes equipped with a premium gooseneck microphone to handle all your in-game communication. The mic''s super cardioid element is excellent at rejecting unwanted ambient noise, so your voice will come through crystal clear every time. There''s even an included windscreen that slips onto the mic to further combat wind and breath noise, if need be. The headset''s 1.2 m (3.9-Feet ) cable includes a simple volume/locking mute switch for easy one-hand operation, and comes with a 2.0 m (6.6-Feet ) extension cable for greater versatility.');